### ISSUE TITLE
Investigate localized settings

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-bulk-magic-link-sender#119]
Some magic links have the whole field settings array localized.
For a secure context this is not advisable as it makes all the fields discoverable.

Goal: only localize the fields that are being used.

**Comment by corsacca** [comment]
@kodinkat can you look at doing this for the assigned contacts  (and groups ?) magic links too.

**Comment by kodinkat** [comment]
> @kodinkat can you look at doing this for the assigned contacts (and groups ?) magic links too.

@corsacca Templates and groups already handled. With regards to `User Contact Updates` magic link types; fields are already hardcoded and localized.
