### ISSUE TITLE
After submit, display alert

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-bulk-magic-link-sender#163]
When a user submits a magic link, display a section at the top of the page that the submit was successful.

Right now a toast is displayed, but way too quickly and then the page is refreshed.
![Screen Recording 2024-05-29 at 2 30 38 PM](https://github.com/DiscipleTools/disciple-tools-bulk-magic-link-sender/assets/24901539/add4ee37-1e4d-4803-adc2-acf457172cc1)

At the top of the magic link: Copy this UI from the twilio plugin:
![image](https://github.com/DiscipleTools/disciple-tools-bulk-magic-link-sender/assets/24901539/21a7cedc-b8ca-49c3-9775-01e1517c5dd0)
https://github.com/DiscipleTools/disciple-tools-channels-twilio/blob/b49e74d06710d57a3c986fdb9ca474b4f9183e97/admin/general-tab.php#L105

With the text: Update Submitted.

**Comment by ahillbilly** [comment]
I'd recommend a bit more explanation text.  If successful: 

Thank you for your successful submission.  You may return to the form and re-submit if changes are needed.
