### ISSUE TITLE
User Group Links

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-bulk-magic-link-sender#51]
![image](https://user-images.githubusercontent.com/24901539/188625446-21210898-e7ef-4ecf-97d6-efb7b8162ee4.png)
Lets switch to passing the vars in the body of the request instead of the url. The template form has this fix. I'm testing this on an instance that has a lot of fields.

- The church health milestones don't appear for me.
- Lets hide the fields with the "hidden" param. Like the creation date and last modified

_Originally posted by @corsacca in https://github.com/DiscipleTools/disciple-tools-bulk-magic-link-sender/issues/47#issuecomment-1238032933_

**Comment by cairocoder01** [comment]
Church health doesn't appear because it is a custom display type and hasn't been implemented for display in the magic link yet.

**Comment by cairocoder01** [comment]
This bug is affecting my users, so I'm going to try to take a look at it unless other progress has already been made on it. @kodinkat

**Comment by kodinkat** [comment]
> This bug is affecting my users, so I'm going to try to take a look at it unless other progress has already been made on it. @kodinkat

Hey @cairocoder01, this is on the TODO list, but not started as yet; however, as it's blocking, will jump onto it ASAP so as to move it along... Will keep you posted.. Thanks.

**Comment by cairocoder01** [comment]
I was able to do it pretty quick. Almost done. I'll push the branch probably tomorrow.

**Comment by kodinkat** [comment]
> I was able to do it pretty quick. Almost done. I'll push the branch probably tomorrow.

Ah, sweet! Good job and thanks for that!
