### ISSUE TITLE
Ability to translate magic link form front end to other languages

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-bulk-magic-link-sender#7]
can be done by passing in a language code in the url. Example : magic-link?lang=fr_FR

Switching language:
https://github.com/DiscipleTools/disciple-tools-prayer-campaigns/blob/5c98d3b84554256a7c9fa2e6dd5a9e91039bb577/magic-links/24hour.php#L347

**Comment by bert958** [comment]
When adding the code to pass a language variable in the url, can you add a hook right after that code so that my plugin will be able to set a language value? Becaues in our use case I need to make sure that no other language is shown than the specific one we want. Super thanks!
