### ISSUE TITLE
emails not arriving

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-bulk-magic-link-sender#77]
This could be on the WP sending side or the deliverability/filtering of the user's inbox.

There is a chance it could also be due to the wrong email address being sent to

**Comment by kodinkat** [comment]
Following further investigation, I can confirm Magic Links Plugin detects and processes **Report Survey Collection Links**.

See attached screenshots - Is the user able to confirm if email sending functionality has been setup correctly within their WP instance and they can successfully send messages to the target email address?

![Screenshot 2023-01-05 at 12 30 44](https://user-images.githubusercontent.com/19330800/210782045-4f7e222a-cf0c-424f-8476-4ff493afa4b6.png)

![Screenshot 2023-01-05 at 12 31 11](https://user-images.githubusercontent.com/19330800/210782068-21566f42-d596-40d7-8a92-9d487a8e7e33.png)

**Comment by squigglybob** [comment]
From what I could gather, emails were sending, but some people were not receiving them.

This could be spam filters, or missplelt email addresses.

**Comment by kodinkat** [comment]
> From what I could gather, emails were sending, but some people were not receiving them.
> 
> This could be spam filters, or missplelt email addresses.

Ah, that might be the case, especially if it was only happening to some and not others.. Please have them sanity check spam-filters are not being applied and correct emails are being used.

**Comment by squigglybob** [comment]
I don't have contact details for Doug, but can probably find them from someone

**Comment by squigglybob** [comment]
Doug has performed some tests with a simple email and has had 100% delivery out of 12 test emails sent.

Once we have pushed these changes live, he will test again and try a full email
