### ISSUE TITLE
Implement Failure Toasts On Submission

### ISSUE THREAD

**Issue by kodinkat** [DiscipleTools/disciple-tools-bulk-magic-link-sender#79]
Similar to the toast shown following a successful submission, implement toasts for failed operations.

**Comment by corsacca** [comment]
@kodinkat  Maybe just show the message?
![image](https://user-images.githubusercontent.com/24901539/213658501-2d745fc1-be0a-4e46-84ee-474b6574b285.png)
I set `payload = {'oeuoeu':'ouoeu'}` to test

**Comment by kodinkat** [comment]
> @kodinkat Maybe just show the message?
> ![image](https://user-images.githubusercontent.com/24901539/213658501-2d745fc1-be0a-4e46-84ee-474b6574b285.png)
> I set `payload = {'oeuoeu':'ouoeu'}` to test on the magic-link-user-app.php

@corsacca ah, ok; will try to recreate and fix....
