### ISSUE TITLE
Smart Link Templates - If Sub-Assigned Then Display List Of Contacts

### ISSUE THREAD

**Issue by kodinkat** [DiscipleTools/disciple-tools-bulk-magic-link-sender#87]
Similar to `User Contacts Update` ML types, templates must also display list of contacts who the smart-link recipient is also sub-assigned to.

![Screenshot 2023-02-16 at 16 52 52](https://user-images.githubusercontent.com/19330800/219437644-aa5fa9c8-b4a9-4186-a3e3-29320842a941.png)

**Comment by corsacca** [comment]
Description: A Magic link that displays the contacts a contact is subassigned to.
This Magic link is sent to Contact A
Contact A is subassigned to:
- Contact B
- Contact C

A list with contact B and contact C is shown and the ability to update the fields for those contacts.

Does this magic link also allow the update of contact A?
